
var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa={},k;for(k in h)h.hasOwnProperty(k)&&(aa[k]=h[k]);var ba=[],ca="./this.program";function da(a,b){throw b;}var ea="",fa;"undefined"!==typeof document&&document.currentScript&&(ea=document.currentScript.src);ea=0!==ea.indexOf("blob:")?ea.substr(0,ea.lastIndexOf("/")+1):"";fa=function(a){document.title=a};var ha=h.print||console.log.bind(console),l=h.printErr||console.warn.bind(console);
for(k in aa)aa.hasOwnProperty(k)&&(h[k]=aa[k]);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);function ia(a){ja||(ja={});ja[a]||(ja[a]=1,l(a))}var ja,ka;h.wasmBinary&&(ka=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!==typeof WebAssembly&&t("no native wasm support detected");
function la(a,b){var c="float";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":u[a>>0]=b;break;case "i8":u[a>>0]=b;break;case "i16":ma[a>>1]=b;break;case "i32":v[a>>2]=b;break;case "i64":na=[b>>>0,(oa=b,1<=+Math.abs(oa)?0<oa?(Math.min(+Math.floor(oa/4294967296),4294967295)|0)>>>0:~~+Math.ceil((oa-+(~~oa>>>0))/4294967296)>>>0:0)];v[a>>2]=na[0];v[a+4>>2]=na[1];break;case "float":x[a>>2]=b;break;case "double":y[a>>3]=b;break;default:t("invalid type for setValue: "+c)}}var pa,qa=!1,ra;
function sa(a,b){a||t("Assertion failed: "+b)}var ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function A(a,b){return a?ua(B,a,b):""}
function va(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}function C(a,b,c){return va(a,B,b,c)}
function wa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function xa(a){var b=wa(a)+1,c=E(b);c&&va(a,u,c,b);return c}function ya(a){var b=wa(a)+1,c=za(b);va(a,u,c,b);return c}var u,B,ma,Aa,v,Ba,x,y,F,Ca=[],Da=[],Ea=[],Fa=[],Ga=[];function Ha(){var a=h.preRun.shift();Ca.unshift(a)}var Ia=0,Ja=null,Ka=null;h.preloadedImages={};h.preloadedAudios={};
function t(a){if(h.onAbort)h.onAbort(a);l(a);qa=!0;ra=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function La(){return G.startsWith("data:application/octet-stream;base64,")}var G;G="FluidScripten.js.wasm";if(!La()){var Ma=G;G=h.locateFile?h.locateFile(Ma,ea):ea+Ma}function Na(){var a=G;try{if(a==G&&ka)return new Uint8Array(ka);throw"both async and sync fetching of the wasm failed";}catch(b){t(b)}}
function Oa(){return ka||"function"!==typeof fetch?Promise.resolve().then(function(){return Na()}):fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return Na()})}
var oa,na,Ra={59980:function(a,b,c){h.SDL2||(h.SDL2={});var d=h.SDL2;d.bf!==h.canvas&&(d.re=h.createContext(h.canvas,!1,!0),d.bf=h.canvas);if(d.w!==a||d.kf!==b||d.mf!==d.re)d.image=d.re.createImageData(a,b),d.w=a,d.kf=b,d.mf=d.re;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=v[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.If!==a&&(d.cf=new Int32Array(a.buffer),d.df=new Uint8Array(a.buffer)),
a=d.cf,c=a.length,a.set(v.subarray(b,b+c)),a=d.df,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.re.putImageData(d.image,0,0);return 0},61435:function(a,b,c,d,e){var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var n=0,p;if("undefined"!==typeof CanvasPixelArray&&b instanceof
CanvasPixelArray)for(p=b.length;n<p;){var q=v[e];b[n]=q&255;b[n+1]=q>>8&255;b[n+2]=q>>16&255;b[n+3]=q>>24&255;e++;n+=4}else b=new Int32Array(b.buffer),p=b.length,b.set(v.subarray(e,e+p));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=E(c.length+1);C(c,d,c.length+1);return d},62424:function(a){h.canvas&&(h.canvas.style.cursor=A(a));return 0},62517:function(){h.canvas&&(h.canvas.style.cursor="none")},62586:function(){return screen.width},
62611:function(){return screen.height},62637:function(){return window.innerWidth},62667:function(){return window.innerHeight},62698:function(a){"undefined"!==typeof fa&&fa(A(a));return 0},62793:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},62930:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},63154:function(a){"undefined"===
typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.je||("undefined"!==typeof AudioContext?b.je=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.je=new webkitAudioContext),b.je&&Pa(b.je));return void 0===b.je?-1:0},63647:function(){return h.SDL2.je.sampleRate},63715:function(a,b,c,d){function e(){}function f(n){void 0!==g.capture.Be&&(clearTimeout(g.capture.Be),g.capture.Be=void 0);g.capture.Fe=g.je.createMediaStreamSource(n);g.capture.le=g.je.createScriptProcessor(b,a,
1);g.capture.le.onaudioprocess=function(p){void 0!==g&&void 0!==g.capture&&(p.outputBuffer.getChannelData(0).fill(0),g.capture.Oe=p.inputBuffer,Qa(c,[d]))};g.capture.Fe.connect(g.capture.le);g.capture.le.connect(g.je.destination);g.capture.stream=n}var g=h.SDL2;g.capture.He=g.je.createBuffer(a,b,g.je.sampleRate);g.capture.He.getChannelData(0).fill(0);g.capture.Be=setTimeout(function(){g.capture.Oe=g.capture.He;Qa(c,[d])},b/g.je.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?
navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},65367:function(a,b,c,d){var e=h.SDL2;e.audio.le=e.je.createScriptProcessor(b,0,a);e.audio.le.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Te=f.outputBuffer,Qa(c,[d]))};e.audio.le.connect(e.je.destination)},65777:function(a,b){for(var c=h.SDL2,d=c.capture.Oe.numberOfChannels,e=0;e<d;++e){var f=c.capture.Oe.getChannelData(e);
if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)la(a+4*g,f[g]);else for(g=0;g<b;++g)la(a+4*(g*d+e),f[g])}},66382:function(a,b){for(var c=h.SDL2,d=c.audio.Te.numberOfChannels,e=0;e<d;++e){var f=c.audio.Te.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=x[a+(g*d+e<<2)>>
2]}},66862:function(a){var b=h.SDL2;if(a){void 0!==b.capture.Be&&clearTimeout(b.capture.Be);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.le&&(b.capture.le.onaudioprocess=function(){},b.capture.le.disconnect(),b.capture.le=void 0);void 0!==b.capture.Fe&&(b.capture.Fe.disconnect(),b.capture.Fe=void 0);void 0!==b.capture.He&&(b.capture.He=void 0);b.capture=void 0}else void 0!=
b.audio.le&&(b.audio.le.disconnect(),b.audio.le=void 0),b.audio=void 0;void 0!==b.je&&void 0===b.audio&&void 0===b.capture&&(b.je.close(),b.je=void 0)}};function Sa(a,b,c){a.addEventListener(b,c,{once:!0})}function Pa(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&Sa(d,c,function(){"suspended"===a.state&&a.resume()})})})}
function Ta(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.jf;"number"===typeof c?void 0===b.De?F.get(c)():F.get(c)(b.De):c(void 0===b.De?null:b.De)}}}function Qa(a,b){if("vi".includes("j")){var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else F.get(a).apply(null,b)}function Ua(a){a instanceof Va||"unwind"==a||(l("exception thrown: "+a),da(1,a))}
function Wa(a){this.Ae=a-16;this.yf=function(b){v[this.Ae+4>>2]=b};this.vf=function(b){v[this.Ae+8>>2]=b};this.wf=function(){v[this.Ae>>2]=0};this.uf=function(){u[this.Ae+12>>0]=0};this.xf=function(){u[this.Ae+13>>0]=0};this.nf=function(b,c){this.yf(b);this.vf(c);this.wf();this.uf();this.xf()}}var Xa=0,Ya=[null,[],[]],Za={},$a;$a=function(){return performance.now()};
function ab(a,b){bb=a;cb=b;if(eb)if(fb||(fb=!0),0==a)H=function(){var d=Math.max(0,gb+b-$a())|0;setTimeout(hb,d)};else if(1==a)H=function(){ib(hb)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}H=function(){setImmediate(hb)}}}
function jb(a,b,c,d,e){function f(){if(g<kb){if(!noExitRuntime)try{lb(ra)}catch(n){Ua(n)}return!1}return!0}sa(!eb,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");eb=a;mb=d;var g=kb;fb=!1;hb=function(){if(!qa)if(0<nb.length){var n=Date.now(),p=nb.shift();p.jf(p.De);if(ob){var q=ob,r=0==q%1?q-1:Math.floor(q);ob=p.Hf?r:(8*q+(r+.5))/9}ha('main loop blocker "'+
p.name+'" took '+(Date.now()-n)+" ms");h.setStatus&&(n=h.statusMessage||"Please wait...",p=ob,q=pb.Kf,p?p<q?h.setStatus(n+" ("+(q-p)+"/"+q+")"):h.setStatus(n):h.setStatus(""));f()&&setTimeout(hb,0)}else f()&&(qb=qb+1|0,1==bb&&1<cb&&0!=qb%cb?H():(0==bb&&(gb=$a()),qa||h.preMainLoop&&!1===h.preMainLoop()||(rb(a),h.postMainLoop&&h.postMainLoop()),f()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.tf&&SDL.audio.tf(),H())))};e||(b&&0<b?ab(0,1E3/b):ab(1,1),H());if(c)throw"unwind";}
function rb(a){if(!qa)try{a()}catch(b){Ua(b)}}function sb(a){setTimeout(function(){rb(a)},1E4)}var fb=!1,H=null,kb=0,eb=null,mb=0,bb=0,cb=0,qb=0,nb=[],pb={},gb,hb,ob,tb=!1,ub=!1,vb=[];
function wb(){function a(){ub=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!xb){xb=!0;try{yb=!0}catch(c){yb=!1,ha("warning: no blob constructor, cannot create blobs with mimetypes")}zb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:yb?null:ha("warning: no BlobBuilder");Ab="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;h.Ze||"undefined"!==typeof Ab||(ha("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.Ze=!0);h.preloadPlugins.push({canHandle:function(c){return!h.Ze&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=null;if(yb)try{g=new Blob([c],{type:Bb(d)}),g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Bb(d)}))}catch(q){ia("Blob constructor present but fails: "+
q+"; falling back to blob builder")}g||(g=new zb,g.append((new Uint8Array(c)).buffer),g=g.getBlob());var n=Ab.createObjectURL(g),p=new Image;p.onload=function(){sa(p.complete,"Image "+d+" could not be decoded");var q=document.createElement("canvas");q.width=p.width;q.height=p.height;q.getContext("2d").drawImage(p,0,0);h.preloadedImages[d]=q;Ab.revokeObjectURL(n);e&&e(c)};p.onerror=function(){ha("Image "+n+" could not be decoded");f&&f()};p.src=n}});h.preloadPlugins.push({canHandle:function(c){return!h.Sf&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function g(D){p||(p=!0,h.preloadedAudios[d]=D,e&&e(c))}function n(){p||(p=!0,h.preloadedAudios[d]=new Audio,f&&f())}var p=!1;if(yb){try{var q=new Blob([c],{type:Bb(d)})}catch(D){return n()}q=Ab.createObjectURL(q);var r=new Audio;r.addEventListener("canplaythrough",function(){g(r)},!1);r.onerror=function(){if(!p){ha("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var D="",I=0,m=0,w=0;w<c.length;w++)for(I=
I<<8|c[w],m+=8;6<=m;){var z=I>>m-6&63;m-=6;D+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[z]}2==m?(D+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(I&3)<<4],D+="=="):4==m&&(D+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(I&15)<<2],D+="=");r.src="data:audio/x-"+d.substr(-3)+";base64,"+D;g(r)}};r.src=q;sb(function(){g(r)})}else return n()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||
b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
function(c){!ub&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Cb(a,b,c,d){if(b&&h.re&&a==h.canvas)return h.re;var e;if(b){var f={antialias:!1,alpha:!1,Ye:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!==typeof Db&&(e=Eb(a,f)))var n=J[e].ve}else n=a.getContext("2d");if(!n)return null;c&&(b||sa("undefined"===typeof K,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.re=n,b&&Fb(e),h.Ef=b,vb.forEach(function(p){p()}),wb());return n}var Gb=!1,Hb=void 0,Ib=void 0;
function Jb(a,b){function c(){tb=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Kb,Hb&&d.requestPointerLock(),tb=!0,Ib?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=Ba[SDL.screen>>2]|8388608),Lb(h.canvas),Mb()):Lb(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Ib?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=Ba[SDL.screen>>2]&
-8388609),Lb(h.canvas),Mb()):Lb(d));if(h.onFullScreen)h.onFullScreen(tb);if(h.onFullscreen)h.onFullscreen(tb)}Hb=a;Ib=b;"undefined"===typeof Hb&&(Hb=!0);"undefined"===typeof Ib&&(Ib=!1);var d=h.canvas;Gb||(Gb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Kb(){if(!tb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Nb=0;function ib(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Nb)Nb=b+1E3/60;else for(;b+2>=Nb;)Nb+=1E3/60;setTimeout(a,Math.max(Nb-b,0))}}
function Bb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Ob=[];function Mb(){var a=h.canvas;Ob.forEach(function(b){b(a.width,a.height)})}
function Lb(a,b,c){b&&c?(a.Ff=b,a.lf=c):(b=a.Ff,c=a.lf);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Ib?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var xb,yb,zb,Ab,L=12288,Pb=!1,Qb=0,Rb=0,Sb=0,M={alpha:!1,depth:!1,stencil:!1,antialias:!1},Tb={},Ub;function Vb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function Wb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Xb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Yb=1,Zb=[],N=[],$b=[],ac=[],O=[],P=[],bc=[],J=[],Q=[],cc={},dc=4;
function R(a){ec||(ec=a)}function fc(a){for(var b=Yb++,c=a.length;c<b;c++)a[c]=null;return b}function gc(a,b,c){for(var d="",e=0;e<a;++e){var f=c?v[c+4*e>>2]:-1;d+=A(v[b+4*e>>2],0>f?void 0:f)}return d}function Eb(a,b){a.Ve||(a.Ve=a.getContext,a.getContext=function(d,e){e=a.Ve(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?hc(c,b):0}
function hc(a,b){var c=fc(J),d={Mf:c,attributes:b,version:b.Ye,ve:a};a.canvas&&(a.canvas.ze=d);J[c]=d;("undefined"===typeof b.ff||b.ff)&&ic(d);return c}function Fb(a){jc=J[a];h.re=K=jc&&jc.ve}function ic(a){a||(a=jc);if(!a.pf){a.pf=!0;var b=a.ve;Vb(b);Wb(b);Xb(b);b.pe=b.getExtension("EXT_disjoint_timer_query");b.Rf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Db={},ec,jc,kc=[],lc=0;
function mc(){for(var a=S.length-1;0<=a;--a)nc(a);S=[];T=[]}var T=[];function oc(a,b,c){function d(g,n){if(g.length!=n.length)return!1;for(var p in g)if(g[p]!=n[p])return!1;return!0}for(var e in T){var f=T[e];if(f.Qe==a&&d(f.Re,c))return}T.push({Qe:a,$e:b,Re:c});T.sort(function(g,n){return g.$e<n.$e})}function pc(a){for(var b=0;b<T.length;++b)T[b].Qe==a&&(T.splice(b,1),--b)}function qc(){if(lc&&rc.we)for(var a=0;a<T.length;++a){var b=T[a];T.splice(a,1);--a;b.Qe.apply(null,b.Re)}}var S=[];
function nc(a){var b=S[a];b.target.removeEventListener(b.ke,b.gf,b.ne);S.splice(a,1)}function V(a){function b(d){++lc;rc=a;qc();a.qe(d);qc();--lc}if(a.oe)a.gf=b,a.target.addEventListener(a.ke,b,a.ne),S.push(a),sc||(Fa.push(mc),sc=!0);else for(var c=0;c<S.length;++c)S[c].target==a.target&&S[c].ke==a.ke&&nc(c--)}function tc(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function uc(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var vc={},sc,rc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic={},Jc=[0,document,window];function W(a){a=2<a?A(a):a;return Jc[a]||document.querySelector(a)}function Kc(a){var b=Lc(),c=za(8),d=c+4,e=za(a.id.length+1);C(a.id,e,a.id.length+1);if(a=W(e))v[c>>2]=a.width,v[d>>2]=a.height;c=[v[c>>2],v[d>>2]];Mc(b);return c}function Nc(a,b,c){a=W(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function Oc(a,b,c){if(a.Gf){var d=Lc(),e=za(a.id.length+1);C(a.id,e,a.id.length+1);Nc(e,b,c);Mc(d)}else a.width=b,a.height=c}
function Pc(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Oc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=n,p||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=p,a.style.paddingLeft=q,a.style.paddingRight=r,a.style.paddingTop=D,a.style.paddingBottom=I,a.style.marginLeft=m,a.style.marginRight=
w,a.style.marginTop=z,a.style.marginBottom=U,document.body.style.margin=db,document.documentElement.style.overflow=Bd,document.body.scroll=Cd,a.style.We=Dd,a.ze&&a.ze.ve.viewport(0,0,d,e),Ic.Ee&&F.get(Ic.Ee)(37,0,Ic.Se))}var c=Kc(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,n=a.style.backgroundColor,p=document.body.style.backgroundColor,q=a.style.paddingLeft,r=a.style.paddingRight,D=a.style.paddingTop,I=a.style.paddingBottom,m=a.style.marginLeft,w=a.style.marginRight,z=a.style.marginTop,U=a.style.marginBottom,
db=document.body.style.margin,Bd=document.documentElement.style.overflow,Cd=document.body.scroll,Dd=a.style.We;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Qc(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function Rc(a){return 0>Jc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Sc(a,b){if(0!=b.Pe||0!=b.Ne){Pc(a);var c=b.zf?innerWidth:screen.width,d=b.zf?innerHeight:screen.height,e=Rc(a),f=e.width;e=e.height;var g=Kc(a),n=g[0];g=g[1];3==b.Pe?(Qc(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Pe&&(c*g<n*d?(f=g*c/n,Qc(a,(d-f)/2,0),d=f):(f=n*d/g,Qc(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.hf&&(a.style.We="pixelated");
f=2==b.Ne?devicePixelRatio:1;0!=b.Ne&&(c=c*f|0,d=d*f|0,Oc(a,c,d),a.ze&&a.ze.ve.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return uc()?-3:-1;Ic=b;b.Ee&&F.get(b.Ee)(37,0,b.Se);return 0}function Tc(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.Ge)a.Ge();else return document.body.requestPointerLock||document.body.Ge?-3:-1;return 0}
function Uc(a,b){y[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)y[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)y[a+8*c+528>>3]="object"===typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)v[a+4*c+1040>>2]="object"===typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];v[a+1296>>2]=b.connected;v[a+1300>>2]=b.index;v[a+8>>2]=b.axes.length;v[a+12>>2]=b.buttons.length;C(b.id,a+1304,64);C(b.mapping,a+1368,64)}var Vc=[];
function Wc(a,b,c,d){for(var e=0;e<a;e++){var f=K[c](),g=f&&fc(d);f?(f.name=g,d[g]=f):R(1282);v[b+4*e>>2]=g}}function Xc(a,b,c,d,e,f,g,n){b=N[b];if(a=K[a](b,c))d=n&&C(a.name,n,d),e&&(v[e>>2]=d),f&&(v[f>>2]=a.size),g&&(v[g>>2]=a.type)}function Yc(a,b){Ba[a>>2]=b;Ba[a+4>>2]=(b-Ba[a>>2])/4294967296}
function Zc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 36345:d=0;break;case 34466:var e=K.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=K.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:R(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:v[b+4*a>>2]=e[a];break;case 2:x[b+4*a>>2]=e[a];break;case 4:u[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){R(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:R(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Yc(b,
d);break;case 0:v[b>>2]=d;break;case 2:x[b>>2]=d;break;case 4:u[b>>0]=d?1:0}}else R(1281)}function $c(a){var b=wa(a)+1,c=E(b);C(a,c,b);return c}function ad(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function bd(a){var b=a.xe,c=a.Me,d;if(!b)for(a.xe=b={},a.af={},d=0;d<K.getProgramParameter(a,35718);++d){var e=K.getActiveUniform(a,d);var f=e.name;e=e.size;var g=ad(f);g=0<g?f.slice(0,g):f;var n=a.Le;a.Le+=e;c[g]=[e,n];for(f=0;f<e;++f)b[n]=f,a.af[n++]=g}}
function X(a){var b=K.Ue;if(b){var c=b.xe[a];"number"===typeof c&&(b.xe[a]=c=K.getUniformLocation(b,b.af[a]+(0<c?"["+c+"]":"")));return c}R(1282)}function cd(a,b,c,d){if(c)if(a=N[a],bd(a),a=K.getUniform(a,X(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:x[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b]}else R(1281)}
function dd(a,b,c,d){if(c)if(a=K.getVertexAttrib(a,b),34975==b)v[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:x[c>>2]=a;break;case 5:v[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b];break;case 5:v[c+4*b>>2]=Math.fround(a[b])}else R(1281)}
function ed(a,b,c,d,e){a-=5120;a=1==a?B:4==a?v:6==a?x:5==a||28922==a?Ba:Aa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=dc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var Y=[],fd=[];function gd(a,b){if(!uc())return-1;a=W(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?lc&&rc.we?Sc(a,b):b.ef?(oc(Sc,1,[a,b]),1):-2:-3:-4}
function hd(a,b){var c={target:W(2),ke:"beforeunload",oe:b,qe:function(d){d=d||event;var e=F.get(b)(28,0,a);e&&(e=A(e));if(e)return d.preventDefault(),d.returnValue=e},ne:!0};V(c)}function jd(a,b,c,d,e,f){xc||(xc=E(256));a={target:W(a),ke:f,oe:d,qe:function(g){g=g||event;var n=g.target.id?g.target.id:"",p=xc;C(tc(g.target),p+0,128);C(n,p+128,128);F.get(d)(e,p,b)&&g.preventDefault()},ne:c};V(a)}
function kd(a,b,c,d,e){zc||(zc=E(280));V({target:a,ke:e,oe:d,qe:function(f){f=f||event;var g=zc,n=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,p=!!n;v[g>>2]=p;v[g+4>>2]=uc();var q=p?n:yc,r=q&&q.id?q.id:"";C(tc(q),g+8,128);C(r,g+136,128);v[g+264>>2]=q?q.clientWidth:0;v[g+268>>2]=q?q.clientHeight:0;v[g+272>>2]=screen.width;v[g+276>>2]=screen.height;p&&(yc=n);F.get(d)(19,g,b)&&f.preventDefault()},ne:c})}
function ld(a,b,c,d,e){Ac||(Ac=E(1432));b={target:W(2),we:!0,ke:e,oe:c,qe:function(f){f=f||event;var g=Ac;Uc(g,f.gamepad);F.get(c)(d,g,a)&&f.preventDefault()},ne:b};V(b)}
function md(a,b,c,d,e,f){Bc||(Bc=E(176));a={target:W(a),we:!0,ke:f,oe:d,qe:function(g){var n=Bc;y[n>>3]=g.timeStamp;var p=n>>2;v[p+2]=g.location;v[p+3]=g.ctrlKey;v[p+4]=g.shiftKey;v[p+5]=g.altKey;v[p+6]=g.metaKey;v[p+7]=g.repeat;v[p+8]=g.charCode;v[p+9]=g.keyCode;v[p+10]=g.which;C(g.key||"",n+44,32);C(g.code||"",n+76,32);C(g.char||"",n+108,32);C(g.locale||"",n+140,32);F.get(d)(e,n,b)&&g.preventDefault()},ne:c};V(a)}
function nd(a,b,c){y[a>>3]=b.timeStamp;a>>=2;v[a+2]=b.screenX;v[a+3]=b.screenY;v[a+4]=b.clientX;v[a+5]=b.clientY;v[a+6]=b.ctrlKey;v[a+7]=b.shiftKey;v[a+8]=b.altKey;v[a+9]=b.metaKey;ma[2*a+20]=b.button;ma[2*a+21]=b.buttons;v[a+11]=b.movementX;v[a+12]=b.movementY;c=Rc(c);v[a+13]=b.clientX-c.left;v[a+14]=b.clientY-c.top}
function od(a,b,c,d,e,f){Cc||(Cc=E(72));a=W(a);V({target:a,we:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,ke:f,oe:d,qe:function(g){g=g||event;nd(Cc,g,a);F.get(d)(e,Cc,b)&&g.preventDefault()},ne:c})}function pd(a,b,c,d,e){Dc||(Dc=E(260));V({target:a,ke:e,oe:d,qe:function(f){f=f||event;var g=Dc,n=document.pointerLockElement||document.rf||document.Pf||document.Nf;v[g>>2]=!!n;var p=n&&n.id?n.id:"";C(tc(n),g+4,128);C(p,g+132,128);F.get(d)(20,g,b)&&f.preventDefault()},ne:c})}
function qd(a,b,c,d){Ec||(Ec=E(36));a=W(a);V({target:a,ke:"resize",oe:d,qe:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var g=Ec;v[g>>2]=e.detail;v[g+4>>2]=f.clientWidth;v[g+8>>2]=f.clientHeight;v[g+12>>2]=innerWidth;v[g+16>>2]=innerHeight;v[g+20>>2]=outerWidth;v[g+24>>2]=outerHeight;v[g+28>>2]=pageXOffset;v[g+32>>2]=pageYOffset;F.get(d)(10,g,b)&&e.preventDefault()}}},ne:c})}
function rd(a,b,c,d,e,f){Fc||(Fc=E(1696));a=W(a);V({target:a,we:"touchstart"==f||"touchend"==f,ke:f,oe:d,qe:function(g){for(var n={},p=g.touches,q=0;q<p.length;++q){var r=p[q];n[r.identifier]=r}p=g.changedTouches;for(q=0;q<p.length;++q)r=p[q],r.qf=1,n[r.identifier]=r;p=g.targetTouches;for(q=0;q<p.length;++q)n[p[q].identifier].sf=1;p=Fc;y[p>>3]=g.timeStamp;r=p>>2;v[r+3]=g.ctrlKey;v[r+4]=g.shiftKey;v[r+5]=g.altKey;v[r+6]=g.metaKey;r+=7;var D=Rc(a),I=0;for(q in n){var m=n[q];v[r]=m.identifier;v[r+1]=
m.screenX;v[r+2]=m.screenY;v[r+3]=m.clientX;v[r+4]=m.clientY;v[r+5]=m.pageX;v[r+6]=m.pageY;v[r+7]=m.qf;v[r+8]=m.sf;v[r+9]=m.clientX-D.left;v[r+10]=m.clientY-D.top;r+=13;if(31<++I)break}v[p+8>>2]=I;F.get(d)(e,p,b)&&g.preventDefault()},ne:c})}
function sd(a,b,c){var d=Jc[1];Gc||(Gc=E(8));V({target:d,ke:"visibilitychange",oe:c,qe:function(e){e=e||event;var f=Gc,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);v[f>>2]=document.hidden;v[f+4>>2]=g;F.get(c)(21,f,a)&&e.preventDefault()},ne:b})}
function td(a,b,c,d){Hc||(Hc=E(104));V({target:a,we:!0,ke:"wheel",oe:d,qe:function(e){e=e||event;var f=Hc;nd(f,e,a);y[f+72>>3]=e.deltaX;y[f+80>>3]=e.deltaY;y[f+88>>3]=e.deltaZ;v[f+96>>2]=e.deltaMode;F.get(d)(9,f,b)&&e.preventDefault()},ne:c})}var ud={};
function vd(){if(!wd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in ud)void 0===ud[b]?delete a[b]:a[b]=ud[b];var c=[];for(b in a)c.push(b+"="+a[b]);wd=c}return wd}var wd;function xd(a){return 0===a%4&&(0!==a%100||0===a%400)}function yd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var zd=[31,29,31,30,31,30,31,31,30,31,30,31],Ad=[31,28,31,30,31,30,31,31,30,31,30,31];function Ed(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(xd(a.getFullYear())?zd:Ad)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Fd(a,b,c,d){function e(m,w,z){for(m="number"===typeof m?m.toString():m||"";m.length<w;)m=z[0]+m;return m}function f(m,w){return e(m,w,"0")}function g(m,w){function z(db){return 0>db?-1:0<db?1:0}var U;0===(U=z(m.getFullYear()-w.getFullYear()))&&0===(U=z(m.getMonth()-w.getMonth()))&&(U=z(m.getDate()-w.getDate()));return U}function n(m){switch(m.getDay()){case 0:return new Date(m.getFullYear()-1,11,29);case 1:return m;case 2:return new Date(m.getFullYear(),0,3);case 3:return new Date(m.getFullYear(),
0,2);case 4:return new Date(m.getFullYear(),0,1);case 5:return new Date(m.getFullYear()-1,11,31);case 6:return new Date(m.getFullYear()-1,11,30)}}function p(m){m=Ed(new Date(m.me+1900,0,1),m.Ke);var w=new Date(m.getFullYear()+1,0,4),z=n(new Date(m.getFullYear(),0,4));w=n(w);return 0>=g(z,m)?0>=g(w,m)?m.getFullYear()+1:m.getFullYear():m.getFullYear()-1}var q=v[d+40>>2];d={Cf:v[d>>2],Bf:v[d+4>>2],Ie:v[d+8>>2],Ce:v[d+12>>2],ye:v[d+16>>2],me:v[d+20>>2],Je:v[d+24>>2],Ke:v[d+28>>2],Tf:v[d+32>>2],Af:v[d+
36>>2],Df:q?A(q):""};c=A(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in q)c=c.replace(new RegExp(r,"g"),q[r]);var D="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
I="January February March April May June July August September October November December".split(" ");q={"%a":function(m){return D[m.Je].substring(0,3)},"%A":function(m){return D[m.Je]},"%b":function(m){return I[m.ye].substring(0,3)},"%B":function(m){return I[m.ye]},"%C":function(m){return f((m.me+1900)/100|0,2)},"%d":function(m){return f(m.Ce,2)},"%e":function(m){return e(m.Ce,2," ")},"%g":function(m){return p(m).toString().substring(2)},"%G":function(m){return p(m)},"%H":function(m){return f(m.Ie,
2)},"%I":function(m){m=m.Ie;0==m?m=12:12<m&&(m-=12);return f(m,2)},"%j":function(m){return f(m.Ce+yd(xd(m.me+1900)?zd:Ad,m.ye-1),3)},"%m":function(m){return f(m.ye+1,2)},"%M":function(m){return f(m.Bf,2)},"%n":function(){return"\n"},"%p":function(m){return 0<=m.Ie&&12>m.Ie?"AM":"PM"},"%S":function(m){return f(m.Cf,2)},"%t":function(){return"\t"},"%u":function(m){return m.Je||7},"%U":function(m){var w=new Date(m.me+1900,0,1),z=0===w.getDay()?w:Ed(w,7-w.getDay());m=new Date(m.me+1900,m.ye,m.Ce);return 0>
g(z,m)?f(Math.ceil((31-z.getDate()+(yd(xd(m.getFullYear())?zd:Ad,m.getMonth()-1)-31)+m.getDate())/7),2):0===g(z,w)?"01":"00"},"%V":function(m){var w=new Date(m.me+1901,0,4),z=n(new Date(m.me+1900,0,4));w=n(w);var U=Ed(new Date(m.me+1900,0,1),m.Ke);return 0>g(U,z)?"53":0>=g(w,U)?"01":f(Math.ceil((z.getFullYear()<m.me+1900?m.Ke+32-z.getDate():m.Ke+1-z.getDate())/7),2)},"%w":function(m){return m.Je},"%W":function(m){var w=new Date(m.me,0,1),z=1===w.getDay()?w:Ed(w,0===w.getDay()?1:7-w.getDay()+1);m=
new Date(m.me+1900,m.ye,m.Ce);return 0>g(z,m)?f(Math.ceil((31-z.getDate()+(yd(xd(m.getFullYear())?zd:Ad,m.getMonth()-1)-31)+m.getDate())/7),2):0===g(z,w)?"01":"00"},"%y":function(m){return(m.me+1900).toString().substring(2)},"%Y":function(m){return m.me+1900},"%z":function(m){m=m.Af;var w=0<=m;m=Math.abs(m)/60;return(w?"+":"-")+String("0000"+(m/60*100+m%60)).slice(-4)},"%Z":function(m){return m.Df},"%%":function(){return"%"}};for(r in q)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),q[r](d)));r=Gd(c);
if(r.length>b)return 0;u.set(r,a);return r.length-1}h.requestFullscreen=function(a,b){Jb(a,b)};h.requestAnimationFrame=function(a){ib(a)};h.setCanvasSize=function(a,b,c){Lb(h.canvas,a,b);c||Mb()};h.pauseMainLoop=function(){H=null;kb++};h.resumeMainLoop=function(){kb++;var a=bb,b=cb,c=eb;eb=null;jb(c,0,!1,mb,!0);ab(a,b);H()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
h.createContext=function(a,b,c,d){return Cb(a,b,c,d)};for(var K,Z=0;32>Z;++Z)Vc.push(Array(Z));var Hd=new Float32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Hd.subarray(0,Z+1);var Id=new Int32Array(288);for(Z=0;288>Z;++Z)fd[Z]=Id.subarray(0,Z+1);function Gd(a){var b=Array(wa(a)+1);va(a,b,0,b.length);return b}
var Kd={yc:function(a){return E(a+16)+16},nc:function(a,b,c){(new Wa(a)).nf(b,c);Xa++;throw a;},R:function(){return 0},Sa:function(){return 0},Ua:function(){},Q:function(){t()},i:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=$a();else return v[Jd()>>2]=28,-1;v[b>>2]=a/1E3|0;v[b+4>>2]=a%1E3*1E6|0;return 0},q:function(){t("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},qa:function(a){if(12448==a)return L=12288,
1;L=12300;return 0},Ca:function(a,b,c,d,e){if(62E3!=a)L=12296,c=0;else{if(b)for(;;){a=v[b>>2];if(12321==a)M.alpha=0<v[b+4>>2];else if(12325==a)M.depth=0<v[b+4>>2];else if(12326==a)M.stencil=0<v[b+4>>2];else if(12337==a)a=v[b+4>>2],M.antialias=0<a;else if(12338==a)a=v[b+4>>2],M.antialias=1==a;else if(12544==a)M.Of=12547!=v[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(v[e>>2]=1),c&&0<d&&(v[c>>2]=62002),L=12288,c=1):(L=12300,c=0)}return c},za:function(a,b,c,d){if(62E3!=a)return L=12296,0;for(a=1;;){b=
v[d>>2];if(12440==b)a=v[d+4>>2];else if(12344==b)break;else return L=12292,0;d+=8}if(2!=a)return L=12293,0;M.Ye=a-1;M.Qf=0;Ub=Eb(h.canvas,M);if(0!=Ub)return L=12288,Fb(Ub),h.Ef=!0,vb.forEach(function(e){e()}),Fb(null),62004;L=12297;return 0},xa:function(a,b){if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;L=12288;return 62006},ya:function(a,b){if(62E3!=a)return L=12296,0;if(62004!=b)return L=12294,0;a=Ub;jc===J[a]&&(jc=null);if("object"===typeof vc)for(var c=J[a].ve.canvas,d=0;d<S.length;++d)S[d].target!=
c||nc(d--);J[a]&&J[a].ve.canvas&&(J[a].ve.canvas.ze=void 0);J[a]=null;L=12288;Qb==b&&(Qb=0);return 1},wa:function(a,b){if(62E3!=a)return L=12296,0;if(62006!=b)return L=12301,1;Rb==b&&(Rb=0);Sb==b&&(Sb=0);L=12288;return 1},Ba:function(a,b,c,d){if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return v[d>>2]=M.alpha?32:24,1;case 12321:return v[d>>2]=M.alpha?8:0,1;case 12322:return v[d>>2]=8,1;case 12323:return v[d>>2]=8,1;case 12324:return v[d>>
2]=8,1;case 12325:return v[d>>2]=M.depth?24:0,1;case 12326:return v[d>>2]=M.stencil?8:0,1;case 12327:return v[d>>2]=12344,1;case 12328:return v[d>>2]=62002,1;case 12329:return v[d>>2]=0,1;case 12330:return v[d>>2]=4096,1;case 12331:return v[d>>2]=16777216,1;case 12332:return v[d>>2]=4096,1;case 12333:return v[d>>2]=0,1;case 12334:return v[d>>2]=0,1;case 12335:return v[d>>2]=12344,1;case 12337:return v[d>>2]=M.antialias?4:0,1;case 12338:return v[d>>2]=M.antialias?1:0,1;case 12339:return v[d>>2]=4,
1;case 12340:return v[d>>2]=12344,1;case 12341:case 12342:case 12343:return v[d>>2]=-1,1;case 12345:case 12346:return v[d>>2]=0,1;case 12347:return v[d>>2]=0,1;case 12348:return v[d>>2]=1;case 12349:case 12350:return v[d>>2]=0,1;case 12351:return v[d>>2]=12430,1;case 12352:return v[d>>2]=4,1;case 12354:return v[d>>2]=0,1;default:return L=12292,0}},M:function(){L=12288;return 62E3},na:function(){return L},Ea:function(a,b,c){if(62E3==a)return b&&(v[b>>2]=1),c&&(v[c>>2]=4),Pb=!0,L=12288,1;L=12296;return 0},
va:function(a,b,c,d){if(62E3!=a)return L=12296,0;if(0!=d&&62004!=d)return L=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return L=12301,0;Fb(d?Ub:null);Qb=d;Sb=b;Rb=c;L=12288;return 1},oa:function(a,b){if(62E3!=a)return L=12296,0;L=12288;if(Tb[b])return Tb[b];switch(b){case 12371:a=xa("Emscripten");break;case 12372:a=xa("1.4 Emscripten EGL");break;case 12373:a=xa("");break;case 12429:a=xa("OpenGL_ES");break;default:return L=12300,0}return Tb[b]=a},ua:function(){if(Pb)if(h.re)if(h.re.isContextLost())L=
12302;else return L=12288,1;else L=12290;else L=12289;return 0},ta:function(a,b){if(62E3!=a)return L=12296,0;0==b?ab(0,0):ab(1,b);L=12288;return 1},Da:function(a){if(62E3!=a)return L=12296,0;Sb=Rb=Qb=0;Pb=!1;L=12288;return 1},ra:function(){L=12288;return 1},sa:function(){L=12288;return 1},a:function(a,b,c){kc.length=0;var d;for(c>>=2;d=B[b++];)(d=105>d)&&c&1&&c++,kc.push(d?y[c++>>1]:v[c]),++c;return Ra[a].apply(null,kc)},ja:function(){if(!uc())return-1;pc(Sc);var a=Jc[1];if(a.exitFullscreen)a.fullscreenElement&&
a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},ma:function(){pc(Tc);if(document.exitPointerLock)document.exitPointerLock();else if(document.Xe)document.Xe();else return-1;return 0},l:function(){return devicePixelRatio},b:function(a,b,c){a=W(a);if(!a)return-4;a=Rc(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},fa:function(a,b){if(0>a||a>=wc.length)return-5;if(!wc[a])return-7;Uc(b,wc[a]);return 0},ga:function(){return wc.length},
Md:function(a){K.activeTexture(a)},Ld:function(a,b){K.attachShader(N[a],P[b])},aa:function(a,b){K.pe.beginQueryEXT(a,Q[b])},Kd:function(a,b,c){K.bindAttribLocation(N[a],b,A(c))},Id:function(a,b){K.bindBuffer(a,Zb[b])},Hd:function(a,b){K.bindFramebuffer(a,$b[b])},Gd:function(a,b){K.bindRenderbuffer(a,ac[b])},Fd:function(a,b){K.bindTexture(a,O[b])},U:function(a){K.bindVertexArray(bc[a])},Ed:function(a,b,c,d){K.blendColor(a,b,c,d)},Dd:function(a){K.blendEquation(a)},Cd:function(a,b){K.blendEquationSeparate(a,
b)},Bd:function(a,b){K.blendFunc(a,b)},Ad:function(a,b,c,d){K.blendFuncSeparate(a,b,c,d)},zd:function(a,b,c,d){K.bufferData(a,c?B.subarray(c,c+b):b,d)},xd:function(a,b,c,d){K.bufferSubData(a,b,B.subarray(d,d+c))},wd:function(a){return K.checkFramebufferStatus(a)},vd:function(a){K.clear(a)},ud:function(a,b,c,d){K.clearColor(a,b,c,d)},td:function(a){K.clearDepth(a)},sd:function(a){K.clearStencil(a)},rd:function(a,b,c,d){K.colorMask(!!a,!!b,!!c,!!d)},qd:function(a){K.compileShader(P[a])},pd:function(a,
b,c,d,e,f,g,n){K.compressedTexImage2D(a,b,c,d,e,f,n?B.subarray(n,n+g):null)},od:function(a,b,c,d,e,f,g,n,p){K.compressedTexSubImage2D(a,b,c,d,e,f,g,p?B.subarray(p,p+n):null)},md:function(a,b,c,d,e,f,g,n){K.copyTexImage2D(a,b,c,d,e,f,g,n)},ld:function(a,b,c,d,e,f,g,n){K.copyTexSubImage2D(a,b,c,d,e,f,g,n)},kd:function(){var a=fc(N),b=K.createProgram();b.name=a;b.ue=b.se=b.te=0;b.Le=1;N[a]=b;return a},jd:function(a){var b=fc(P);P[b]=K.createShader(a);return b},id:function(a){K.cullFace(a)},hd:function(a,
b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Zb[d];e&&(K.deleteBuffer(e),e.name=0,Zb[d]=null)}},gd:function(a,b){for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=$b[d];e&&(K.deleteFramebuffer(e),e.name=0,$b[d]=null)}},fd:function(a){if(a){var b=N[a];b?(K.deleteProgram(b),b.name=0,N[a]=null):R(1281)}},da:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(K.pe.deleteQueryEXT(e),Q[d]=null)}},ed:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=ac[d];e&&(K.deleteRenderbuffer(e),e.name=0,ac[d]=
null)}},dd:function(a){if(a){var b=P[a];b?(K.deleteShader(b),P[a]=null):R(1281)}},bd:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=O[d];e&&(K.deleteTexture(e),e.name=0,O[d]=null)}},Td:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2];K.deleteVertexArray(bc[d]);bc[d]=null}},ad:function(a){K.depthFunc(a)},$c:function(a){K.depthMask(!!a)},_c:function(a,b){K.depthRange(a,b)},Zc:function(a,b){K.detachShader(N[a],P[b])},Yc:function(a){K.disable(a)},Xc:function(a){K.disableVertexAttribArray(a)},
Wc:function(a,b,c){K.drawArrays(a,b,c)},Pd:function(a,b,c,d){K.drawArraysInstanced(a,b,c,d)},Qd:function(a,b){for(var c=Vc[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];K.drawBuffers(c)},Vc:function(a,b,c,d){K.drawElements(a,b,c,d)},Od:function(a,b,c,d,e){K.drawElementsInstanced(a,b,c,d,e)},Uc:function(a){K.enable(a)},Tc:function(a){K.enableVertexAttribArray(a)},$:function(a){K.pe.endQueryEXT(a)},Sc:function(){K.finish()},Rc:function(){K.flush()},Qc:function(a,b,c,d){K.framebufferRenderbuffer(a,b,c,ac[d])},Pc:function(a,
b,c,d,e){K.framebufferTexture2D(a,b,c,O[d],e)},Oc:function(a){K.frontFace(a)},Nc:function(a,b){Wc(a,b,"createBuffer",Zb)},Lc:function(a,b){Wc(a,b,"createFramebuffer",$b)},ea:function(a,b){for(var c=0;c<a;c++){var d=K.pe.createQueryEXT();if(!d){for(R(1282);c<a;)v[b+4*c++>>2]=0;break}var e=fc(Q);d.name=e;Q[e]=d;v[b+4*c>>2]=e}},Kc:function(a,b){Wc(a,b,"createRenderbuffer",ac)},Ic:function(a,b){Wc(a,b,"createTexture",O)},Sd:function(a,b){Wc(a,b,"createVertexArray",bc)},Mc:function(a){K.generateMipmap(a)},
Hc:function(a,b,c,d,e,f,g){Xc("getActiveAttrib",a,b,c,d,e,f,g)},Gc:function(a,b,c,d,e,f,g){Xc("getActiveUniform",a,b,c,d,e,f,g)},Fc:function(a,b,c,d){a=K.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);v[c>>2]=e;for(b=0;b<e;++b)v[d+4*b>>2]=P.indexOf(a[b])},Ec:function(a,b){return K.getAttribLocation(N[a],A(b))},Dc:function(a,b){Zc(a,b,4)},Cc:function(a,b,c){c?v[c>>2]=K.getBufferParameter(a,b):R(1281)},Bc:function(){var a=K.getError()||ec;ec=0;return a},Ac:function(a,b){Zc(a,b,2)},zc:function(a,
b,c,d){a=K.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;v[d>>2]=a},xc:function(a,b){Zc(a,b,0)},vc:function(a,b,c,d){a=K.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,d,b):0;c&&(v[c>>2]=b)},wc:function(a,b,c){if(c)if(a>=Yb)R(1281);else if(a=N[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.ue)for(b=0;b<K.getProgramParameter(a,35718);++b)a.ue=Math.max(a.ue,
K.getActiveUniform(a,b).name.length+1);v[c>>2]=a.ue}else if(35722==b){if(!a.se)for(b=0;b<K.getProgramParameter(a,35721);++b)a.se=Math.max(a.se,K.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.se}else if(35381==b){if(!a.te)for(b=0;b<K.getProgramParameter(a,35382);++b)a.te=Math.max(a.te,K.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.te}else v[c>>2]=K.getProgramParameter(a,b);else R(1281)},W:function(a,b,c){if(c){a=K.pe.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Yc(c,d)}else R(1281)},
Y:function(a,b,c){if(c){a=K.pe.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else R(1281)},V:function(a,b,c){if(c){a=K.pe.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Yc(c,d)}else R(1281)},X:function(a,b,c){if(c){a=K.pe.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else R(1281)},Z:function(a,b,c){c?v[c>>2]=K.pe.getQueryEXT(a,b):R(1281)},uc:function(a,b,c){c?v[c>>2]=K.getRenderbufferParameter(a,b):R(1281)},sc:function(a,b,c,
d){a=K.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,d,b):0;c&&(v[c>>2]=b)},rc:function(a,b,c,d){a=K.getShaderPrecisionFormat(a,b);v[c>>2]=a.rangeMin;v[c+4>>2]=a.rangeMax;v[d>>2]=a.precision},qc:function(a,b,c,d){if(a=K.getShaderSource(P[a]))b=0<b&&d?C(a,d,b):0,c&&(v[c>>2]=b)},tc:function(a,b,c){c?35716==b?(a=K.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(P[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=K.getShaderParameter(P[a],
b):R(1281)},pc:function(a){var b=cc[a];if(!b){switch(a){case 7939:b=K.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=$c(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=K.getParameter(a))||R(1280);b=b&&$c(b);break;case 7938:b=$c("OpenGL ES 2.0 ("+K.getParameter(7938)+")");break;case 35724:b=K.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=
$c(b);break;default:R(1280)}cc[a]=b}return b},oc:function(a,b,c){c?x[c>>2]=K.getTexParameter(a,b):R(1281)},mc:function(a,b,c){c?v[c>>2]=K.getTexParameter(a,b):R(1281)},jc:function(a,b){b=A(b);if(a=N[a]){bd(a);var c=a.xe,d=0,e=b,f=ad(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Me[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else R(1281);return-1},lc:function(a,b,c){cd(a,b,c,2)},kc:function(a,b,c){cd(a,b,c,0)},gc:function(a,b,c){c?v[c>>2]=K.getVertexAttribOffset(a,
b):R(1281)},ic:function(a,b,c){dd(a,b,c,2)},hc:function(a,b,c){dd(a,b,c,5)},fc:function(a,b){K.hint(a,b)},ec:function(a){return(a=Zb[a])?K.isBuffer(a):0},dc:function(a){return K.isEnabled(a)},bc:function(a){return(a=$b[a])?K.isFramebuffer(a):0},ac:function(a){return(a=N[a])?K.isProgram(a):0},ba:function(a){return(a=Q[a])?K.pe.isQueryEXT(a):0},$b:function(a){return(a=ac[a])?K.isRenderbuffer(a):0},_b:function(a){return(a=P[a])?K.isShader(a):0},Zb:function(a){return(a=O[a])?K.isTexture(a):0},Rd:function(a){return(a=
bc[a])?K.isVertexArray(a):0},Yb:function(a){K.lineWidth(a)},Xb:function(a){a=N[a];K.linkProgram(a);a.xe=0;a.Me={}},Wb:function(a,b){3317==a&&(dc=b);K.pixelStorei(a,b)},Vb:function(a,b){K.polygonOffset(a,b)},_:function(a,b){K.pe.queryCounterEXT(Q[a],b)},Ub:function(a,b,c,d,e,f,g){(g=ed(f,e,c,d,g))?K.readPixels(a,b,c,d,e,f,g):R(1280)},Sb:function(){},Rb:function(a,b,c,d){K.renderbufferStorage(a,b,c,d)},Qb:function(a,b){K.sampleCoverage(a,!!b)},Pb:function(a,b,c,d){K.scissor(a,b,c,d)},Ob:function(){R(1280)},
Nb:function(a,b,c,d){b=gc(b,c,d);K.shaderSource(P[a],b)},Mb:function(a,b,c){K.stencilFunc(a,b,c)},Lb:function(a,b,c,d){K.stencilFuncSeparate(a,b,c,d)},Kb:function(a){K.stencilMask(a)},Jb:function(a,b){K.stencilMaskSeparate(a,b)},Ib:function(a,b,c){K.stencilOp(a,b,c)},Hb:function(a,b,c,d){K.stencilOpSeparate(a,b,c,d)},Gb:function(a,b,c,d,e,f,g,n,p){K.texImage2D(a,b,c,d,e,f,g,n,p?ed(n,g,d,e,p):null)},Fb:function(a,b,c){K.texParameterf(a,b,c)},Eb:function(a,b,c){K.texParameterf(a,b,x[c>>2])},Db:function(a,
b,c){K.texParameteri(a,b,c)},Cb:function(a,b,c){K.texParameteri(a,b,v[c>>2])},Bb:function(a,b,c,d,e,f,g,n,p){var q=null;p&&(q=ed(n,g,e,f,p));K.texSubImage2D(a,b,c,d,e,f,g,n,q)},Ab:function(a,b){K.uniform1f(X(a),b)},zb:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);K.uniform1fv(X(a),d)},xb:function(a,b){K.uniform1i(X(a),b)},wb:function(a,b,c){if(288>=b)for(var d=fd[b-1],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);K.uniform1iv(X(a),
d)},vb:function(a,b,c){K.uniform2f(X(a),b,c)},ub:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);K.uniform2fv(X(a),d)},tb:function(a,b,c){K.uniform2i(X(a),b,c)},sb:function(a,b,c){if(144>=b)for(var d=fd[2*b-1],e=0;e<2*b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2];else d=v.subarray(c>>2,c+8*b>>2);K.uniform2iv(X(a),d)},rb:function(a,b,c,d){K.uniform3f(X(a),b,c,d)},qb:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<
3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);K.uniform3fv(X(a),d)},pb:function(a,b,c,d){K.uniform3i(X(a),b,c,d)},ob:function(a,b,c){if(96>=b)for(var d=fd[3*b-1],e=0;e<3*b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2];else d=v.subarray(c>>2,c+12*b>>2);K.uniform3iv(X(a),d)},mb:function(a,b,c,d,e){K.uniform4f(X(a),b,c,d,e)},lb:function(a,b,c){if(72>=b){var d=Y[4*b-1],e=x;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];
d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);K.uniform4fv(X(a),d)},kb:function(a,b,c,d,e){K.uniform4i(X(a),b,c,d,e)},jb:function(a,b,c){if(72>=b)for(var d=fd[4*b-1],e=0;e<4*b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2];else d=v.subarray(c>>2,c+16*b>>2);K.uniform4iv(X(a),d)},ib:function(a,b,c,d){if(72>=b)for(var e=Y[4*b-1],f=0;f<4*b;f+=4)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>
2];else e=x.subarray(d>>2,d+16*b>>2);K.uniformMatrix2fv(X(a),!!c,e)},hb:function(a,b,c,d){if(32>=b)for(var e=Y[9*b-1],f=0;f<9*b;f+=9)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2],e[f+4]=x[d+(4*f+16)>>2],e[f+5]=x[d+(4*f+20)>>2],e[f+6]=x[d+(4*f+24)>>2],e[f+7]=x[d+(4*f+28)>>2],e[f+8]=x[d+(4*f+32)>>2];else e=x.subarray(d>>2,d+36*b>>2);K.uniformMatrix3fv(X(a),!!c,e)},gb:function(a,b,c,d){if(18>=b){var e=Y[16*b-1],f=x;d>>=2;for(var g=0;g<16*b;g+=16){var n=d+g;e[g]=
f[n];e[g+1]=f[n+1];e[g+2]=f[n+2];e[g+3]=f[n+3];e[g+4]=f[n+4];e[g+5]=f[n+5];e[g+6]=f[n+6];e[g+7]=f[n+7];e[g+8]=f[n+8];e[g+9]=f[n+9];e[g+10]=f[n+10];e[g+11]=f[n+11];e[g+12]=f[n+12];e[g+13]=f[n+13];e[g+14]=f[n+14];e[g+15]=f[n+15]}}else e=x.subarray(d>>2,d+64*b>>2);K.uniformMatrix4fv(X(a),!!c,e)},fb:function(a){a=N[a];K.useProgram(a);K.Ue=a},eb:function(a){K.validateProgram(N[a])},db:function(a,b){K.vertexAttrib1f(a,b)},bb:function(a,b){K.vertexAttrib1f(a,x[b>>2])},ab:function(a,b,c){K.vertexAttrib2f(a,
b,c)},$a:function(a,b){K.vertexAttrib2f(a,x[b>>2],x[b+4>>2])},_a:function(a,b,c,d){K.vertexAttrib3f(a,b,c,d)},Za:function(a,b){K.vertexAttrib3f(a,x[b>>2],x[b+4>>2],x[b+8>>2])},Ya:function(a,b,c,d,e){K.vertexAttrib4f(a,b,c,d,e)},Xa:function(a,b){K.vertexAttrib4f(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},Nd:function(a,b){K.vertexAttribDivisor(a,b)},Wa:function(a,b,c,d,e,f){K.vertexAttribPointer(a,b,c,!!d,e,f)},Va:function(a,b,c,d){K.viewport(a,b,c,d)},d:function(){return 0},Ka:function(a,b,c){B.copyWithin(a,
b,b+c)},ka:function(a,b,c){return gd(a,{Pe:v[c>>2],Ne:v[c+4>>2],hf:v[c+8>>2],ef:b,Ee:v[c+12>>2],Se:v[c+16>>2]})},L:function(a,b){a=W(a);return a?a.requestPointerLock||a.Ge?lc&&rc.we?Tc(a):b?(oc(Tc,2,[a]),1):-2:-1:-4},La:function(){t("OOM")},ha:function(){return(wc=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},r:function(a,b,c){if("undefined"===typeof onbeforeunload)return-1;if(1!==c)return-5;hd(a,b);return 0},D:function(a,b,c,d){jd(a,
b,c,d,12,"blur");return 0},f:Nc,o:function(a,b,c){a=W(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},E:function(a,b,c,d){jd(a,b,c,d,13,"focus");return 0},u:function(a,b,c,d){if(!uc())return-1;a=W(a);if(!a)return-4;kd(a,b,c,d,"fullscreenchange");kd(a,b,c,d,"webkitfullscreenchange");return 0},k:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;ld(a,b,c,26,"gamepadconnected");return 0},j:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;
ld(a,b,c,27,"gamepaddisconnected");return 0},x:function(a,b,c,d){md(a,b,c,d,2,"keydown");return 0},v:function(a,b,c,d){md(a,b,c,d,1,"keypress");return 0},w:function(a,b,c,d){md(a,b,c,d,3,"keyup");return 0},cc:function(a,b,c){a=F.get(a);jb(a,b,c)},J:function(a,b,c,d){od(a,b,c,d,5,"mousedown");return 0},H:function(a,b,c,d){od(a,b,c,d,33,"mouseenter");return 0},G:function(a,b,c,d){od(a,b,c,d,34,"mouseleave");return 0},K:function(a,b,c,d){od(a,b,c,d,8,"mousemove");return 0},I:function(a,b,c,d){od(a,b,
c,d,6,"mouseup");return 0},y:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Xe||document.body.rf||document.body.Ge))return-1;a=W(a);if(!a)return-4;pd(a,b,c,d,"pointerlockchange");pd(a,b,c,d,"mozpointerlockchange");pd(a,b,c,d,"webkitpointerlockchange");pd(a,b,c,d,"mspointerlockchange");return 0},t:function(a,b,c,d){qd(a,b,c,d);return 0},z:function(a,b,c,d){rd(a,b,c,d,25,"touchcancel");return 0},B:function(a,b,c,d){rd(a,b,c,d,23,"touchend");return 0},
A:function(a,b,c,d){rd(a,b,c,d,24,"touchmove");return 0},C:function(a,b,c,d){rd(a,b,c,d,22,"touchstart");return 0},s:function(a,b,c){sd(a,b,c);return 0},F:function(a,b,c,d){a=W(a);return"undefined"!==typeof a.onwheel?(td(a,b,c,d),0):-1},c:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Qa:function(a){for(var b=$a();$a()-b<a;);},Oa:function(a,b){var c=0;vd().forEach(function(d,e){var f=b+c;e=v[a+4*e>>2]=f;for(f=0;f<d.length;++f)u[e++>>
0]=d.charCodeAt(f);u[e>>0]=0;c+=d.length+1});return 0},Pa:function(a,b){var c=vd();v[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});v[b>>2]=d;return 0},S:function(){return 0},Ra:function(a,b,c,d){a=Za.Lf(a);b=Za.Jf(a,b,c);v[d>>2]=b;return 0},Ja:function(){},Ta:function(a,b,c,d){for(var e=0,f=0;f<c;f++){for(var g=v[b+8*f>>2],n=v[b+(8*f+4)>>2],p=0;p<n;p++){var q=B[g+p],r=Ya[a];0===q||10===q?((1===a?ha:l)(ua(r,0)),r.length=0):r.push(q)}e+=n}v[d>>2]=e;return 0},h:function(a){var b=Date.now();
v[a>>2]=b/1E3|0;v[a+4>>2]=b%1E3*1E3|0;return 0},la:function(a){K.activeTexture(a)},O:function(a,b){K.attachShader(N[a],P[b])},n:function(a,b){K.bindBuffer(a,Zb[b])},e:function(a,b){K.bindTexture(a,O[b])},Aa:function(a,b){K.blendFunc(a,b)},Tb:function(a,b,c,d){K.bufferData(a,c?B.subarray(c,c+b):b,d)},cb:function(a){K.compileShader(P[a])},Ia:function(){var a=fc(N),b=K.createProgram();b.name=a;b.ue=b.se=b.te=0;b.Le=1;N[a]=b;return a},yb:function(a){var b=fc(P);P[b]=K.createShader(a);return b},p:function(a){if(a){var b=
N[a];b?(K.deleteProgram(b),b.name=0,N[a]=null):R(1281)}},g:function(a){if(a){var b=P[a];b?(K.deleteShader(b),P[a]=null):R(1281)}},yd:function(a,b,c){K.drawArrays(a,b,c)},Ga:function(a){K.enable(a)},Jd:function(a){K.enableVertexAttribArray(a)},Vd:function(a,b){Wc(a,b,"createBuffer",Zb)},nd:function(a,b){Wc(a,b,"createTexture",O)},Fa:function(a,b,c,d){a=K.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,d,b):0;c&&(v[c>>2]=b)},N:function(a,b,c){if(c)if(a>=Yb)R(1281);else if(a=N[a],
35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.ue)for(b=0;b<K.getProgramParameter(a,35718);++b)a.ue=Math.max(a.ue,K.getActiveUniform(a,b).name.length+1);v[c>>2]=a.ue}else if(35722==b){if(!a.se)for(b=0;b<K.getProgramParameter(a,35721);++b)a.se=Math.max(a.se,K.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.se}else if(35381==b){if(!a.te)for(b=0;b<K.getProgramParameter(a,35382);++b)a.te=Math.max(a.te,K.getActiveUniformBlockName(a,b).length+
1);v[c>>2]=a.te}else v[c>>2]=K.getProgramParameter(a,b);else R(1281)},Ma:function(a,b,c,d){a=K.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,d,b):0;c&&(v[c>>2]=b)},T:function(a,b,c){c?35716==b?(a=K.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(P[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=K.getShaderParameter(P[a],b):R(1281)},ca:function(a,b){b=A(b);if(a=N[a]){bd(a);var c=a.xe,d=0,e=b,f=ad(b);0<f&&(d=parseInt(b.slice(f+1))>>>
0,e=b.slice(0,f));if((e=a.Me[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else R(1281);return-1},Ha:function(a){a=N[a];K.linkProgram(a);a.xe=0;a.Me={}},nb:function(a,b,c,d){b=gc(b,c,d);K.shaderSource(P[a],b)},cd:function(a,b,c,d,e,f,g,n,p){K.texImage2D(a,b,c,d,e,f,g,n,p?ed(n,g,d,e,p):null)},m:function(a,b,c){K.texParameteri(a,b,c)},Jc:function(a,b,c,d,e,f,g,n,p){var q=null;p&&(q=ed(n,g,e,f,p));K.texSubImage2D(a,b,c,d,e,f,g,n,q)},ia:function(a,b){K.uniform1i(X(a),b)},pa:function(a){a=
N[a];K.useProgram(a);K.Ue=a},Ud:function(a,b,c,d,e,f){K.vertexAttribPointer(a,b,c,!!d,e,f)},P:function(){},Na:function(a,b,c,d){return Fd(a,b,c,d)}};
(function(){function a(e){h.asm=e.exports;pa=h.asm.Wd;e=pa.buffer;h.HEAP8=u=new Int8Array(e);h.HEAP16=ma=new Int16Array(e);h.HEAP32=v=new Int32Array(e);h.HEAPU8=B=new Uint8Array(e);h.HEAPU16=Aa=new Uint16Array(e);h.HEAPU32=Ba=new Uint32Array(e);h.HEAPF32=x=new Float32Array(e);h.HEAPF64=y=new Float64Array(e);F=h.asm.ce;Da.unshift(h.asm.Xd);Ia--;h.monitorRunDependencies&&h.monitorRunDependencies(Ia);0==Ia&&(null!==Ja&&(clearInterval(Ja),Ja=null),Ka&&(e=Ka,Ka=null,e()))}function b(e){a(e.instance)}function c(e){return Oa().then(function(f){return WebAssembly.instantiate(f,
d)}).then(function(f){return f}).then(e,function(f){l("failed to asynchronously prepare wasm: "+f);t(f)})}var d={a:Kd};Ia++;h.monitorRunDependencies&&h.monitorRunDependencies(Ia);if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return l("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ka||"function"!==typeof WebAssembly.instantiateStreaming||La()||"function"!==typeof fetch?c(b):fetch(G,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){l("wasm streaming compile failed: "+f);l("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();h.___wasm_call_ctors=function(){return(h.___wasm_call_ctors=h.asm.Xd).apply(null,arguments)};h._main=function(){return(h._main=h.asm.Yd).apply(null,arguments)};
var E=h._malloc=function(){return(E=h._malloc=h.asm.Zd).apply(null,arguments)},Jd=h.___errno_location=function(){return(Jd=h.___errno_location=h.asm._d).apply(null,arguments)},Lc=h.stackSave=function(){return(Lc=h.stackSave=h.asm.$d).apply(null,arguments)},Mc=h.stackRestore=function(){return(Mc=h.stackRestore=h.asm.ae).apply(null,arguments)},za=h.stackAlloc=function(){return(za=h.stackAlloc=h.asm.be).apply(null,arguments)};h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.de).apply(null,arguments)};
h.dynCall_ji=function(){return(h.dynCall_ji=h.asm.ee).apply(null,arguments)};h.dynCall_viijii=function(){return(h.dynCall_viijii=h.asm.fe).apply(null,arguments)};h.dynCall_iiiiij=function(){return(h.dynCall_iiiiij=h.asm.ge).apply(null,arguments)};h.dynCall_iiiiijj=function(){return(h.dynCall_iiiiijj=h.asm.he).apply(null,arguments)};h.dynCall_iiiiiijj=function(){return(h.dynCall_iiiiiijj=h.asm.ie).apply(null,arguments)};var Ld;
function Va(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ka=function Md(){Ld||Nd();Ld||(Ka=Md)};
function Nd(a){function b(){if(!Ld&&(Ld=!0,h.calledRun=!0,!qa)){Ta(Da);Ta(Ea);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(Od){var c=a,d=h._main;c=c||[];var e=c.length+1,f=za(4*(e+1));v[f>>2]=ya(ca);for(var g=1;g<e;g++)v[(f>>2)+g]=ya(c[g-1]);v[(f>>2)+e]=0;try{var n=d(e,f);lb(n)}catch(p){Ua(p)}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)c=h.postRun.shift(),Ga.unshift(c);Ta(Ga)}}a=a||ba;if(!(0<Ia)){if(h.preRun)for("function"==typeof h.preRun&&
(h.preRun=[h.preRun]);h.preRun.length;)Ha();Ta(Ca);0<Ia||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=Nd;function lb(a){ra=ra=a;if(!noExitRuntime){if(h.onExit)h.onExit(a);qa=!0}da(a,new Va(a))}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Od=!0;h.noInitialRun&&(Od=!1);Nd();
